name: dart_extensions_methods
description: "Extensions for different types similar to kotlin. Methods for the next set of types: String, bool, Iterable, List. Also contains some global extensions and class Pair"
version: 1.1.1
homepage: https://github.com/mishatron/dart_extensions.git

environment:
  sdk: ">=2.6.0 <3.0.0"
